#define EOF_T		0
#define EOL_T		1
#define VARIABLE_T 	2
#define INT_T 		3
#define FLOAT_T 	4
#define STRING_T	5
#define OPERATOR_T 	6
#define SYMBOL_T	7
#define FOR_T		8
#define WHILE_T		9
#define FN_T		10
#define RETURN_T	11
#define IMPORT_T	12
#define CIMPORT_T	13
#define IF_T		14
#define ELIF_T		15
#define ELSE_T		16
#define BEAK_T		17
#define CONTINUE_T	18
