/* TAG */
#define EOF_T		0
#define EOL_T		1
#define VARIABLE_T 	2
#define INT_T 		3
#define FLOAT_T 	4
#define STRING_T	5
#define OPERATOR_T 	6
#define SYMBOL_T	7
#define FOR_T		8
#define WHILE_T		9
#define FN_T		10
#define RETURN_T	11
#define IMPORT_T	12
#define IF_T		13
#define ELIF_T		14
#define ELSE_T		15
#define BREAK_T		16
#define CONTINUE_T	17

/* TAG2 */
#define ADD_OPR_T 18
#define SUB_OPR_T 19
#define MUL_OPR_T 20
#define DIV_OPR_T 21
#define MOD_OPR_T 22
#define AND_OPR_T 23
#define OR_OPR_T 24
#define XOR_OPR_T 25
#define CGREATER_OPR_T 26
#define CLESS_OPR_T 27
#define ASSIGNMENT_OPR_T 28
#define INC_OPR_T 29
#define DEC_OPR_T 30
#define MUL_ASSIGN_OPR_T 31
#define DIV_ASSIGN_OPR_T 32
#define MOD_ASSIGN_OPR_T 33
#define AND_ASSIGN_OPR_T 34
#define OR_ASSIGN_OPR_T 35
#define XOR_ASSIGN_OPR_T 36
#define CGREATER_EQU_OPR_T 37
#define CLESS_EQU_OPR_T 38
#define CEQU_OPR_T 39
#define LAND_OPR_T 40
#define LOR_OPR_T 41
#define SHR_OPR_T 42
#define SHL_OPR_T 43
#define SHR_ASSIGN_OPR_T 44
#define SHL_ASSIGN_OPR_T 45

#define MAX_TOKEN_VALUE 50
#define INIT_DSTR_SPACE 2048
